version: '3'

services:
  booking-service:
    build: ./booking-service/
    volumes:
      - ./booking-service:/usr/src/app
    ports:
      - 5001:5000
    container_name: booking-service-container
  availability-service:
    build: availability-service/
    volumes:
      - ./availability-service:/usr/src/app
    ports:
      - 5002:5000
    container_name: availability-service-container
  pricing-service:
    build: pricing-service/
    volumes:
      - ./pricing-service:/usr/src/app
    ports:
      - 5003:5000
    container_name: pricing-service-container
  ranking-service:
    build: ranking-service/
    volumes:
      - ./ranking-service:/usr/src/app
    ports:
      - 5004:5000
    container_name: ranking-service-container
  query-display-service:
    build: query-display-service/
    volumes:
      - ./query-display-service:/usr/src/app
    ports:
      - 5006:5000
    container_name: query-display-service-container
  krakend-service:
    image: devopsfaith/krakend:1.1.1
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    depends_on:
      - availability-service
      - pricing-service
      - ranking-service
      - booking-service
      - query-display-service